spring:
  config:
    import: classpath:discount-policies.yml

  datasource:
    url: jdbc:postgresql://postgres-db:5432/shopping_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: always

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
